OK - "Success" : "Amex" - ""Success (MkCreditCard {number = "374245*****0126", name = MkCardName "Test Last", validTo = (5,2026), ccv = ***, metaData = Nothing})
FAIL - "Failure" : "Amex" - ""Success (MkCreditCard {number = "378282*****0005", name = MkCardName "Test Last", validTo = (5,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "Argencard" - "AR/ARS"Success (MkCreditCard {number = "501105******7827", name = MkCardName "Test Last", validTo = (12,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "Cabal" - "\tAR/ARS"Success (MkCreditCard {number = "627170******9642", name = MkCardName "Test Last", validTo = (3,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "Cencosud" - "\tAR/ARS"Success (MkCreditCard {number = "603493******3614", name = MkCardName "Test Last", validTo = (6,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "China Union Pay" - "\tCN/USD"Success (MkCreditCard {number = "625094******8599", name = MkCardName "Test Last", validTo = (6,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "Discover" - "\tUS/USD"Success (MkCreditCard {number = "601155*******9458", name = MkCardName "Test Last", validTo = (12,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "Discover" - "\tUS/USD"Success (MkCreditCard {number = "601100******0009", name = MkCardName "Test Last", validTo = (12,2026), ccv = ***, metaData = Just (MkCardMeta {schema = Discover, cardType = Credit, cardBrand = Nothing, issuerCountry = Nothing, issuer = Nothing})})
OK - "Success" : "ELO" - "\tBR/BRL"Success (MkCreditCard {number = "636297*****5701", name = MkCardName "Test Last", validTo = (8,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "Hipercard" - "\tBR/BR"Success (MkCreditCard {number = "606282*****7663", name = MkCardName "Test Last", validTo = (9,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "JC" - "JP/JPY"Success (MkCreditCard {number = "356600******0410", name = MkCardName "Test Last", validTo = (2,2026), ccv = ***, metaData = Nothing})
FAIL - "Failure" : "JC" - "\tJP/JPY"Success (MkCreditCard {number = "353011******0000", name = MkCardName "Test Last", validTo = (3,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "Mastercard" - ""Success (MkCreditCard {number = "542523******9903", name = MkCardName "Test Last", validTo = (4,2026), ccv = ***, metaData = Nothing})
FAIL - "Invalid exp. date" : "Mastercard" - ""Failure Wrong value for valid date: "12/202"
OK - "Success" : "Mastercard" - ""Success (MkCreditCard {number = "222242******1113", name = MkCardName "Test Last", validTo = (8,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "Mastercard" - ""Success (MkCreditCard {number = "222300******0010", name = MkCardName "Test Last", validTo = (9,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "Naranja" - "AR/ARS"Success (MkCreditCard {number = "589562******5650", name = MkCardName "Test Last", validTo = (11,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "Nativa" - "AR/ARs"Success (MkCreditCard {number = "520053******7118", name = MkCardName "Test Last", validTo = (11,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "Tarjet Shopping" - "AR/ARS"Success (MkCreditCard {number = "603488******9896", name = MkCardName "Test Last", validTo = (9,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "Visa" - ""Success (MkCreditCard {number = "426398******9299", name = MkCardName "Test Last", validTo = (2,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "Visa" - ""Success (MkCreditCard {number = "426398******9299", name = MkCardName "Test Last", validTo = (4,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "Visa" - ""Success (MkCreditCard {number = "426398******9299", name = MkCardName "Test Last", validTo = (2,2026), ccv = ***, metaData = Nothing})
FAIL - "Failure" : "Visa" - "ARS/EUR/USD"Success (MkCreditCard {number = "491748******7107", name = MkCardName "Test Last", validTo = (1,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "Visa" - "BR/BRL"Success (MkCreditCard {number = "400191******7193", name = MkCardName "Test Last", validTo = (9,2026), ccv = ***, metaData = Nothing})
OK - "Success" : "Visa" - "BR/BRL"Success (MkCreditCard {number = "400770******2454", name = MkCardName "Test Last", validTo = (10,2026), ccv = ***, metaData = Just (MkCardMeta {schema = Visa, cardType = Credit, cardBrand = Nothing, issuerCountry = Nothing, issuer = Nothing})})
OK - "Success" : "Visa Debit Card" - ""Success (MkCreditCard {number = "470132******1234", name = MkCardName "Test Last", validTo = (12,2026), ccv = ***, metaData = Just (MkCardMeta {schema = Visa, cardType = Debit, cardBrand = Nothing, issuerCountry = Nothing, issuer = Nothing})})
FAIL - "Failure" : "Visa Debit Card" - ""Success (MkCreditCard {number = "434769******7777", name = MkCardName "Test Last", validTo = (1,2026), ccv = ***, metaData = Just (MkCardMeta {schema = Visa, cardType = Debit, cardBrand = Nothing, issuerCountry = Nothing, issuer = Nothing})})
